version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    tty: true
    stdin_open: true
    command: npm run dev
    ports:
      - '3030:3000' # To avoid port conflict with api.
